development:
  adapter: postgresql
  host: localhost
  username: postgres
  password: bonebreak1
  database: trapsmart_development
  encoding: UTF8

test:
  adapter: postgresql
  host: localhost
  username: postgres
  password: bonebreak1
  database: trapsmart_test
  encoding: UTF8

production:
  default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5